// <auto-generated />
using System;
using AdiNeydiProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdiNeydiProject.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20230406102850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdiNeydiProject.DAL.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("Post_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Audio_pkey");

                    b.ToTable("Audio", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("Category_pkey");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Created_Time");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("Ip_Address");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("Post_ID");

                    b.Property<int?>("RepliedCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("RepliedComment_ID");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<bool?>("TrueComment")
                        .HasColumnType("boolean")
                        .HasColumnName("trueComment");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Comment_pkey");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Like", b =>
                {
                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("Post_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("Post_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Picture_pkey");

                    b.ToTable("Picture", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("Category_ID");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Created_Time");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IsApproved")
                        .HasColumnType("text")
                        .HasColumnName("Is_Approved");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("Type_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("Post_pkey");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("Type_pkey");

                    b.ToTable("Type", (string)null);
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CreatedTime")
                        .HasColumnType("date")
                        .HasColumnName("Created_Time");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("character(80)")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_Active");

                    b.Property<string>("IsPhoneVerificated")
                        .HasColumnType("text")
                        .HasColumnName("Is_Phone_Verificated");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .HasMaxLength(80)
                        .HasColumnType("character(80)")
                        .IsFixedLength();

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("character(30)")
                        .IsFixedLength();

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("UserType_ID");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdiNeydiProject.DAL.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("UserType_pkey");

                    b.ToTable("UserType", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
